config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks do
    collection do
      post :confirm
    end
  end

  resources :labels, only: [:new, :create, :index, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  namespace :admin do
    resources :users
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels

  accepts_nested_attributes_for :task_labels, allow_destroy: true

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :status, presence: true
  validates :priority, presence: true

  enum status: {
    waiting: 0,
    working: 1,
    done: 2
  }
  enum priority: {
    low: 0,
    middle: 1,
    high: 2
  }

  scope :search_title, -> (title) { where('title LIKE?', "%#{title}%") }
  scope :search_status, -> (status) { where(status: status) }
  scope :search_label, -> (label) { where(id: TaskLabel.where(label_id: label).pluck(:task_id)) }
  scope :sorted, -> { order(created_at: :DESC) }
  scope :sorted_deadline, -> { order(deadline: :DESC) }
  scope :sorted_priority, -> { order(priority: :DESC) }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i(show edit update destroy)
  before_action :limit_access, only: %i(edit update destroy)
  before_action :authenticate_user, only: %i(index)

  def index
    if params[:title].blank? && params[:status] == '' && params[:label_id].blank?
      redirect_to tasks_path, notice: t('view.flash.search')
    elsif params[:sort_expired]
      @tasks = current_user.tasks.page(params[:page]).per(8).sorted_deadline
    elsif params[:sort_priority]
      @tasks = current_user.tasks.page(params[:page]).per(8).sorted_priority
    elsif params[:title].blank? && params[:status] && params[:label_id].blank?
      @tasks = current_user.tasks.page(params[:page]).per(8).search_status(params[:status]).sorted
    elsif params[:title] && params[:status].blank? && params[:label_id].blank?
      @tasks = current_user.tasks.page(params[:page]).per(8).search_title(params[:title]).sorted
    elsif params[:title].blank? && params[:status].blank? && params[:label_id]
      @tasks = current_user.tasks.page(params[:page]).per(8).search_label(params[:label_id]).sorted
    elsif params[:title] && params[:status].blank? && params[:label_id]
      @tasks = current_user.tasks.page(params[:page]).per(8).search_title(params[:title]).search_label(params[:label_id]).sorted
    elsif params[:title].blank? && params[:status] && params[:label_id]
      @tasks = current_user.tasks.page(params[:page]).per(8).search_status(params[:status]).search_label(params[:label_id]).sorted
    elsif params[:title] && params[:status] && params[:label_id]
      @tasks = current_user.tasks.page(params[:page]).per(8).search_title(params[:title]).search_status(params[:status]).search_label(params[:label_id]).sorted
    else
      @tasks = current_user.tasks.page(params[:page]).per(8).sorted
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path, notice: t('view.flash.save')
      else
        render :new
      end
    end
end

  def show; end

  def edit; end

  def confirm
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: t('view.flash.update')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: t('view.flash.delete')
  end

  private

  def task_params
    params.require(:task).permit(
      :title,
      :content,
      :deadline,
      :status,
      :priority,
      label_ids: []
    )
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def limit_access
    task = Task.find_by(id: params[:id])
      redirect_to tasks_path, notice: t('view.flash.limit_access') unless @task.user_id == current_user.id
    end

  def authenticate_user
    current_user = User.find_by(id: session[:user_id])
    if current_user.nil?
      flash[:notice] = t('view.flash.authenticate_user')
      redirect_to new_session_path
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tasks_path
    elsif action_name == 'edit' || action_name == 'update'
      task_path
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true, url: choose_new_or_edit) do |form| %>
<% if @task.errors.any? %>
  <ul>
    <% @task.errors.full_messages.each do |message| %>
     <li class="error_messages"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="form-group ml-3 my-4">
  <p><span class="bold"><%= form.label :title %></p>
  <%= form.text_field :title, class:"form-control col-4" %>
</div>
<div class="form-group ml-3 my-4">
  <p><span class="bold"><%= form.label :content %></p>
  <%= form.text_field :content, class:"form-control col-4" %>
</div>
<div class="form-group ml-3 my-4">
  <p><span class="bold"><%= form.label :deadline %></p>
  <%= form.datetime_select :deadline, class:"form-control col-4" %>
</div>
<div class="row ml-3 my-4">
  <div class="form-group mr-3">
    <p><span class="bold"><%= form.label :status %></p>
    <%= form.select :status, options_for_select(Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}, selected: Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}),  include_blank: true %>
  </div>
  <div class="form-group ml-3">
    <p><span class="bold"><%= form.label :priority %></p>
    <%= form.select :priority, options_for_select(Task.priorities.keys.map {|k| [I18n.t("enums.task.priority.#{k}"), k]}),  include_blank: true %>
  </div>
</div>
<div class="form-group ml-3 my-4">
  <p><span class="bold"><%= form.label :label_ids, t('view.task.label') %></p>
  <%= form.collection_check_boxes(:label_ids, Label.where(user_id: nil), :id, :label_name) %>
</div>

<% if current_user.labels.present? %>
  <div class="form-group ml-3 my-4" id="label-test">
    <p><span class="bold"><%= form.label :label_ids, t('view.task.custom_label') %></p>
    <%= form.collection_check_boxes(:label_ids, Label.where(user_id: current_user.id), :id, :label_name) %>
  </div>
<% end %>
  <%= form.submit t('view.create'), class: "btn btn-primary btn-lg ml-3 my-4" %>
<% end %>

app/views/tasks/confirm.html.erb
<h3><%= t('view.create_confirm') %></h3>
<div class="row my-4 ml-3">
<%= form_with(model: @task, url: tasks_path, local: true) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.hidden_field :deadline %>
  <%= f.hidden_field :status %>
  <%= f.hidden_field :priority %>
  <%= f.hidden_field 'task[label_ids][]' %>

  <p><%= "#{t('view.task.name')}：#{@task.title}" %></p>
  <p><%= "#{t('view.task.content')}：#{@task.content}" %></p>
  <p><%= "#{t('view.task.deadline')}：#{@task.deadline}" %></p>
  <p><%= "#{t('view.task.status')}：#{@task.human_attribute_enum(:status)}" %></p>
  <p><%= "#{t('view.task.priority')}：#{@task.human_attribute_enum(:priority)}" %></p>
  <p><%= t('view.task.label') %>：</p>
  <%= f.collection_check_boxes(:label_ids, Label.where(user_id: nil), :id, :label_name) %>
  <br>
  <%= f.submit t('view.create'), class: "btn btn-primary btn-lg my-2" %><br>
  <%= f.submit t('view.back'), name: 'back', class: "btn btn-info my-3" %>
<% end %>
</div>

app/views/tasks/edit.html.erb
<h1><%= t('view.task.edit_task') %></h1>
<%= render 'form' %>
<button class="btn btn-info ml-3 my-3"><%= link_to t('view.show'), task_path %></button>
<button class="btn btn-info ml-1 my-3"><%= link_to t('view.back'), tasks_path %></button>

app/views/tasks/index.html.erb
<h1><%= t('view.task.index_task') %></h1>

<%= form_with(url: tasks_path, method: :get, local: true) do |form| %>
  <div class="row align-content-md-center ml-1 mb-5">
    <div class="col-md-3">
      <p><span class="bold"><%= form.label :title, t('view.task.name')  %></p>
      <%= form.text_field :title %>
    </div>
    <div class="col-md-2">
      <p><span class="bold"><%= form.label :status, t('view.task.status') %></p>
      <%= form.select :status, options_for_select(Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}), include_blank: true %>
    </div>
    <div class="col-md-3">
      <p><span class="bold"><%= form.label :label_id, t('view.task.label') %></p>
      <%= form.select :label_id, Label.pluck(:label_name, :id), include_blank: true %>
    </div>
    <div class="col-md-3">
    <br>
      <%= form.submit t('view.search'), id: "searchbutton", class: "btn btn-primary btn-lg" %>
      </div>
  </div>
<% end %>
<div class="row mx-3 my-1">
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th class="align-middle"><%= t('view.task.name') %></th>
      <th class="align-middle"><%= t('view.task.content') %></th>
      <th class="align-middle"><%= t('view.task.deadline') %></th>
      <th class="align-middle"><%= t('view.task.status') %></th>
      <th class="align-middle"><%= t('view.task.priority') %></th>
      <th class="align-middle"><%= t('view.task.show_task') %></th>
      <th class="align-middle"><%= t('view.task.edit_task') %></th>
      <th class="align-middle"><%= t('view.task.delete_task') %></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr class="task_row">
        <td class="align-middle"><%= task.title %></td>
        <td class="align-middle"><%= task.content %></td>
        <td class="align-middle"><%= task.deadline %></td>
        <td class="align-middle"><%= task.human_attribute_enum(:status) %></td>
        <td class="align-middle"><%= task.human_attribute_enum(:priority) %></td>
        <td class="align-middle"><%= link_to t('view.show'), task_path(task.id), class: "btn btn-info" %></td>
        <td class="align-middle"><%= link_to t('view.edit'), edit_task_path(task.id), class: "btn btn-info" %></td>
        <td class="align-middle"><%= link_to t('view.delete'), task_path(task.id), method: :delete, data: { confirm: t('view.delete_confirm') }, class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="row justify-content-around">
  <%= paginate @tasks %>
</div>
<button class="btn btn-primary ml-4 my-4"><%= link_to t('view.sorted_deadline'), tasks_path(sort_expired: "true") %></button>
<button class="btn btn-primary ml-1 my-4"><%= link_to t('view.sorted_priority'), tasks_path(sort_priority: "true") %></button>
<button class="btn btn-info ml-1 my-4"><%= link_to t('view.create_task'), new_task_path %></button>
<button class="btn btn-info ml-1 my-4"><%= link_to t('view.create_label'), labels_path %></button>

app/views/tasks/new.html.erb
<h1><%= t('view.task.new_task') %></h1>
<%= render 'form' %>
<button class="btn btn-info ml-3 my-3"><%= link_to t('view.back'), tasks_path %></button>

app/views/tasks/show.html.erb
<h1><%= t('view.task.content') %></h1>

<div class="ml-3 mb-5">
<p><%= t('view.task.name') %>:<%= @task.title %></p>
<p><%= t('view.task.content') %>:<%= @task.content %></p>
<p><%= t('view.task.deadline') %>:<%= @task.deadline %></p>
<p><%= t('view.task.status') %>:<%= @task.human_attribute_enum(:status) %></p>
<p><%= t('view.task.priority') %>:<%= @task.human_attribute_enum(:priority) %></p>
<p><%= t('view.task.label') %>:</p>
<ul>
<% @task.labels.each do |label| %>
  <li><%= label.label_name %></li>
<% end %>
</ul>
</div>
<button class="btn btn-info ml-3 mb-3"><%= link_to t('view.back'), tasks_path %></button>