config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks do
    collection do
      post :confirm
    end
  end

  resources :labels, only: [:new, :create, :index, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  namespace :admin do
    resources :users
  end
end

app/models/label.rb
class Label < ApplicationRecord
  validates :label_name, presence: true, length: { maximum:50 }
  validates :label_name, uniqueness: true

  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels
  belongs_to :user, optional: true
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def index
    @labels = Label.where(user_id: current_user.id)
    @labels_general = Label.where(user_id: nil) if current_user.admin == true
  end

  def  new
    @label = Label.new
  end

  def create
    @label = current_user.labels.build(label_params)
    if @label.save
      redirect_to labels_path, notice: t('view.flash.label_save')
    else
      render :new
    end
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy
    redirect_to labels_path, notice: t('view.flash.label_delete')
  end

  private

  def label_params
    params.require(:label).permit(:label_name)
  end
end

app/views/labels/index.html.erb
<h1><%= t('view.task.index_label') %></h1>

<div class="row mx-3 my-1">
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th class="align-middle"><%= t('view.task.label') %></th>
      <th class="align-middle"><%= t('view.task.delete_label') %></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
    <tr>
      <td class="align-middle"><%= label.label_name %></td>
      <td class="align-middle"><%= link_to t('view.delete'), label_path(label.id), method: :delete, data: { confirm: t('view.delete_confirm') }, class: "btn btn-warning" %></td>
    <% end %>
    </tr>
    <% if current_user_admin? %>
      <% @labels_general.each do |label| %>
      <tr>
        <td class="align-middle"><%= label.label_name %></td>
        <td class="align-middle"><%= link_to t('view.delete'), label_path(label.id), method: :delete, data: { confirm: t('view.delete_confirm') }, class: "btn btn-warning" %></td>
      <% end %>
    <% end %>
    </tr>
  </tbody>
</table>
</div>
<button class="btn btn-info ml-3 my-4"><%= link_to t('view.create_label'), new_label_path %></button>
<button class="btn btn-outline-dark ml-1 my-4"><%= link_to t('view.index'), tasks_path %></button>

app/views/labels/new.html.erb
<%= form_with(model:@label, local: true ) do |form| %>
<% if @label.errors.any? %>
  <ul>
    <% @label.errors.full_messages.each do |message| %>
     <li class="error_messages"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="form-group ml-3 my-4">
  <p><span class="bold"><%= form.label :label_name, t('view.task.label') %></p>
  <%= form.text_field :label_name, class:"form-control col-4" %>
</div>

  <%= form.submit t('view.create'), class: "btn btn-primary btn-lg ml-3 my-4" %>
<% end %>
<button class="btn btn-info ml-3 my-4"><%= link_to t('view.task.index_label'), labels_path %></button>