config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks do
    collection do
      post :confirm
    end
  end

  resources :labels, only: [:new, :create, :index, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-md navbar-dark" style="background-color:#889bb3;">
        <a class="navbar-brand" href="#">
          <img src="<%= asset_path "notebook.png" %>" width="30" height="30" alt="">
          <%= t('view.task_app') %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">　
          <% if logged_in? %>

          <li class="nav-item"><%= link_to t('view.task.index_task'), tasks_path %></li>
          <li class="nav-item"><%= link_to t('view.profile'), user_path(current_user.id) %></li>
          <li class="nav-item"><%= link_to t('view.logout'), session_path(current_user.id), method: :delete %></li>
        <% else %>
          <li class="nav-item"><%= link_to t('view.sign_up'), new_user_path %></li>
          <li class="nav-item"><%= link_to t('view.login'), new_session_path %></li>
        <% end %>
        </ul>
        </div>
      </nav>
    <div class="container-fluid">
      <% if logged_in? && @current_user.try(:admin?) %>
        <button class="btn btn-primary btn-lg ml-1 my-4"><%= link_to t('view.account_management'), admin_users_path %></button>
      <% end %>
      <% if flash.notice %>
        <div class="alert alert-info">
          <%= flash.notice %><button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
      <% elsif flash.alert %>
        <div class="alert alert-warning">
          <%= flash.alert %><button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
      <% end %>
      <%= yield %>
      </div>
      <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy;2020 TaskApp.</p>
      </div>
    </footer>
  </body>
</html>